services:
  user-service:
    image: ${DOCKER_REGISTRY-}user-service
    build:
      context: .
      dockerfile: UserService/Dockerfile

  user-service-db:
    image: postgres:latest

  product-service:
    image: ${DOCKER_REGISTRY-}product-service
    build:
      context: .
      dockerfile: ProductService/Dockerfile

  product-service-db:
    image: postgres:latest

networks:
  mynetwork:
    driver: bridge

volumes:
  user_service_postgres_data:
  product_service_postgres_data:
