services:
  user-service:
    environment:
      - ConnectionStrings__DefaultConnection=Host=user-service-db;Port=5432;Database=user-service-db;Username=postgres;Password=mysecretpassword
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "6000:8080"
      - "6001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - user-service-db

  user-service-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=user-service-db
    ports:
      - "5432:5432"
    volumes:
      - user_service_postgres_data:/var/lib/postgresql/data

  product-service:
    environment:
      - ConnectionStrings__DefaultConnection=Host=product-service-db;Port=5432;Database=product-service-db;Username=postgres;Password=mysecretpassword
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - PublicKeyUrl=http://user-service:8080/api/users/public-key
    ports:
      - "6010:8080"
      - "6011:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - product-service-db

  product-service-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=product-service-db
    ports:
      - "5433:5432"
    volumes:
      - product_service_postgres_data:/var/lib/postgresql/data

  cart-service:
    environment:
      - ConnectionStrings__Database=Host=cart-service-db;Port=5432;Database=cart-service-db;Username=postgres;Password=mysecretpassword
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - PublicKeyUrl=http://user-service:8080/api/users/public-key
      - ProductServiceUrl=https://product-service:8081
      - PaymentServiceUrl=https://payment-service:8081
      - ConnectionStrings__Redis=distributed-cache:6379
    ports:
      - "6020:8080"
      - "6021:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - cart-service-db
      - distributed-cache

  cart-service-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=cart-service-db
    ports:
      - "5434:5432"
    volumes:
      - cart_service_postgres_data:/var/lib/postgresql/data

  order-service:
    environment:
      - ConnectionStrings__Database=Host=order-service-db;Port=5432;Database=order-service-db;Username=postgres;Password=mysecretpassword
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - PublicKeyUrl=http://user-service:8080/api/users/public-key
      - ProductServiceUrl=https://product-service:8081
      - PaymentServiceUrl=https://payment-service:8081
      - ConnectionStrings__Redis=distributed-cache:6379
    ports:
      - "6040:8080"
      - "6041:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - order-service-db
      - distributed-cache

  order-service-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=order-service-db
    ports:
      - "5435:5432"
    volumes:
      - order_service_postgres_data:/var/lib/postgresql/data

  distributed-cache:
    restart: always
    ports:
      - "6379:6379"

  payment-service:
    environment:
      - Stripe__PublishableKey=your_stripe_public_key
      - Stripe__SecretKey=your_stripe_secret_key
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "6030:8080"
      - "6031:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
